#markdown: rdiscount
permalink: /:title/
url: https://waveletbob.github.io
#highlighter: pygments
highlighter: rouge
gems: [jekyll-paginate]
paginate: 50
paginate_path: "page:num"
name: 邹小波
description: :))) | Talk is so cheap, show me the code.
author: waveletbob
email: waveletbob@gmail.com
duoshuo: waveletbob
weibo: 1911291317 
hub: waveletbob 
safe: false
about: "留余"
